lobby:
  spawn:
    world: "world"
    x: 0
    y: 64
    z: 0
    yaw: 0
    pitch: 0
  allow_build: false
  allow_fly_default: false
  allow_size_default: true

items:
  boarding_ticket:
    slot: 1
    id: 340
    name: "Boarding Ticket"
    action: "server_selector"
  airport_staff:
    slot: 2
    id: 369
    name: "Airport Staff"
    action: "staff_gui"
  luggage:
    slot: 7
    id: 355
    name: "Luggage"
    action: "cosmetics"
  access_card:
    slot: 8
    id: 280
    name: "Access Card"
    action: "shop"
  phone:
    slot: 9
    id: 364
    name: "Your Phone"
    action: "profile"
